name: Non-Default Branch Push CI (Python)

on:
  push:
    branches-ignore: ['main']
    paths-ignore: ['README.md']
  pull_request:
    types: [opened, reopened, synchronize]  
    paths-ignore: ['README.md']


jobs:
  branch-ci:
    uses: openclimatefix/.github/.github/workflows/branch_ci.yml@add-set-up-python
    secrets: inherit
    with:
      enable_linting: true
      enable_typechecking: false
      tests_folder: tests
      tests_conda_deps: "libsqlite esmf esmpy"
      test_python_versions: '["3.12"]'
